### ISSUE TITLE
[BE/Task] 스키마 및 API

### ISSUE THREAD

**Issue by woobaeh** [codestates/DogGain#46]
### ISSUE
- Group:  `server`
- Type: `feature`
- Detail: fix actions from client redux

### TODO
1. [x] API 작성 툴 (Swagger, Postman, Gitbook API) 을 사용하여 요청/응답 및 JSON 키/값 형식 기술
2. [x] ERD (DB Diagram) 작성
3. [x] ORM 사용 (sequelize, typeorm 권장)
