### ISSUE TITLE
[FE/Task] 로그인, 마이페이지, 회원가입, 회원정보수정 백엔드와 연결

### ISSUE THREAD

**Issue by L9628** [codestates/DogGain#48]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인, 마이페이지, 회원가입, 회원정보수정 백엔드와 연결

### TODO
1. [ ] 로그인 백엔드와 연결
2. [ ] 마이페이지 백엔드와 연결
3. [ ] 회원가입 백엔드와 연결
4. [ ] 회원정보수정 백엔드와 연결

### Labels
- Estimated time: `E: 9h`
- Group : `client`
- Sprint: `3`
- Urgency: `High`
