### ISSUE TITLE
[FE/Task] 크롤링 컴포넌트에 api를 axios로 연결

### ISSUE THREAD

**Issue by Ensil-dev** [codestates/DogGain#49]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: axios를 이용해 데이터베이스에서 database_doggain을 받아와서 useEffect로 크롤링컴포넌트에 props로 전달합니다.

### TODO
1. [x] axios를 이용해서 데이터 받아오기
2. [x] useEffect를 통해 조건, 실행문 작성하기
3. [x] props로 전달될 정보 확인하기
